//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reunion.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reunion.Web.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutViewTitle {
            get {
                return ResourceManager.GetString("AboutViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting participants.
        /// </summary>
        public static string AcceptedParticipants {
            get {
                return ResourceManager.GetString("AcceptedParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will attend the reunion..
        /// </summary>
        public static string AcceptFinalDate {
            get {
                return ResourceManager.GetString("AcceptFinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Account_RememberMe {
            get {
                return ResourceManager.GetString("Account_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string Account_RememberThisBrowser {
            get {
                return ResourceManager.GetString("Account_RememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string AccountChangePassword {
            get {
                return ResourceManager.GetString("AccountChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string AccountChangePasswordForm {
            get {
                return ResourceManager.GetString("AccountChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string AccountChangeTitle {
            get {
                return ResourceManager.GetString("AccountChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string AccountChangeYourPassword {
            get {
                return ResourceManager.GetString("AccountChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click here to log in.
        /// </summary>
        public static string AccountClickHerToLogin {
            get {
                return ResourceManager.GetString("AccountClickHerToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string AccountClickingHere {
            get {
                return ResourceManager.GetString("AccountClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string AccountConfirmEmail {
            get {
                return ResourceManager.GetString("AccountConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string AccountConfirmNewPassword {
            get {
                return ResourceManager.GetString("AccountConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string AccountConfirmPassword {
            get {
                return ResourceManager.GetString("AccountConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunion - confirm your account.
        /// </summary>
        public static string AccountConfirmYourAccount {
            get {
                return ResourceManager.GetString("AccountConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AccountCreateNew {
            get {
                return ResourceManager.GetString("AccountCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string AccountCreateNewAccount {
            get {
                return ResourceManager.GetString("AccountCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string AccountCurrentPassword {
            get {
                return ResourceManager.GetString("AccountCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string AccountEmailLink {
            get {
                return ResourceManager.GetString("AccountEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string AccountEnterVerificationCode {
            get {
                return ResourceManager.GetString("AccountEnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string AccountEnterYourEmail {
            get {
                return ResourceManager.GetString("AccountEnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string AccountErrFailedToVerifyPhone {
            get {
                return ResourceManager.GetString("AccountErrFailedToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string AccountErrInvalidCode {
            get {
                return ResourceManager.GetString("AccountErrInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string AccountErrInvalidLoginAttempt {
            get {
                return ResourceManager.GetString("AccountErrInvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string AccountErrNewPasswordAndConfirmationNotMatch {
            get {
                return ResourceManager.GetString("AccountErrNewPasswordAndConfirmationNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string AccountErrorLengthTooShort {
            get {
                return ResourceManager.GetString("AccountErrorLengthTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string AccountErrPasswordAndConfirmationNotMatch {
            get {
                return ResourceManager.GetString("AccountErrPasswordAndConfirmationNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string AccountForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("AccountForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string AccountForgotSubject {
            get {
                return ResourceManager.GetString("AccountForgotSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string AccountForgotYourPassword {
            get {
                return ResourceManager.GetString("AccountForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string AccountManage {
            get {
                return ResourceManager.GetString("AccountManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string AccountPleaseCheckYourEmail {
            get {
                return ResourceManager.GetString("AccountPleaseCheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click here to {0}.
        /// </summary>
        public static string AccountPleaseClickHereToLogin1 {
            get {
                return ResourceManager.GetString("AccountPleaseClickHereToLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string AccountPleaseClickHereToLogin2 {
            get {
                return ResourceManager.GetString("AccountPleaseClickHereToLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking {0}.
        /// </summary>
        public static string AccountPleaseConfirmYourAccount {
            get {
                return ResourceManager.GetString("AccountPleaseConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click {0} to reset your password..
        /// </summary>
        public static string AccountPleaseResetYourPassword {
            get {
                return ResourceManager.GetString("AccountPleaseResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string AccountRegister {
            get {
                return ResourceManager.GetString("AccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string AccountRegisterNewUser {
            get {
                return ResourceManager.GetString("AccountRegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string AccountResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("AccountResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string AccountResetYourPassword {
            get {
                return ResourceManager.GetString("AccountResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        public static string AccountSelectTwoFactor {
            get {
                return ResourceManager.GetString("AccountSelectTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string AccountSendCodeTitle {
            get {
                return ResourceManager.GetString("AccountSendCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string AccountSendVerificationCode {
            get {
                return ResourceManager.GetString("AccountSendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email..
        /// </summary>
        public static string AccountThankYouForConfirmingYourEmail {
            get {
                return ResourceManager.GetString("AccountThankYouForConfirmingYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string AccountVerify {
            get {
                return ResourceManager.GetString("AccountVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string AccountYourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("AccountYourPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string AccountYourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("AccountYourPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string AccountYourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("AccountYourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string AccountYourPhoneNumberWasAdded {
            get {
                return ResourceManager.GetString("AccountYourPhoneNumberWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string AccountYourPhoneNumberWasRemoved {
            get {
                return ResourceManager.GetString("AccountYourPhoneNumberWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is:.
        /// </summary>
        public static string AccountYourSecurityCodeIs {
            get {
                return ResourceManager.GetString("AccountYourSecurityCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string AccountYourTwoFactorAuthenticationProviderHasBeenSet {
            get {
                return ResourceManager.GetString("AccountYourTwoFactorAuthenticationProviderHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string AcountLogin {
            get {
                return ResourceManager.GetString("AcountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your action is required.
        /// </summary>
        public static string ActionRequired {
            get {
                return ResourceManager.GetString("ActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this participant.
        /// </summary>
        public static string AddThisParticipant {
            get {
                return ResourceManager.GetString("AddThisParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local court.
        /// </summary>
        public static string Amtsgericht {
            get {
                return ResourceManager.GetString("Amtsgericht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered.
        /// </summary>
        public static string Answered {
            get {
                return ResourceManager.GetString("Answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEOs.
        /// </summary>
        public static string Ceos {
            get {
                return ResourceManager.GetString("Ceos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a date for the event, yet.
        ///Please check and update the following days: {0}.
        /// </summary>
        public static string CheckDays {
            get {
                return ResourceManager.GetString("CheckDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to be completely removed from the list of participants of this meeting?.
        /// </summary>
        public static string ConfirmCompleteRejection {
            get {
                return ResourceManager.GetString("ConfirmCompleteRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmailViewTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really can not come on {0} ?.
        /// </summary>
        public static string ConfirmFinaldateRejection {
            get {
                return ResourceManager.GetString("ConfirmFinaldateRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to take the {0} for your reunion ?.
        /// </summary>
        public static string ConfirmFinalInvitation {
            get {
                return ResourceManager.GetString("ConfirmFinalInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to leave that page, without saving your changes ?.
        /// </summary>
        public static string ConfirmLeavePage {
            get {
                return ResourceManager.GetString("ConfirmLeavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First contact only via my email address.
        /// </summary>
        public static string ContactFirstTimePersonally {
            get {
                return ResourceManager.GetString("ContactFirstTimePersonally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactViewTitle {
            get {
                return ResourceManager.GetString("ContactViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new reunion.
        /// </summary>
        public static string CreateNewReunion {
            get {
                return ResourceManager.GetString("CreateNewReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reunion will take place.
        /// </summary>
        public static string DateFound {
            get {
                return ResourceManager.GetString("DateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Date Proposals.
        /// </summary>
        public static string DateRanking {
            get {
                return ResourceManager.GetString("DateRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusing participants.
        /// </summary>
        public static string DeactivatedParticipants {
            get {
                return ResourceManager.GetString("DeactivatedParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline of planning.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline must be in future.
        /// </summary>
        public static string DeadlineMustBeInFuture {
            get {
                return ResourceManager.GetString("DeadlineMustBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunion canceled.
        /// </summary>
        public static string DeadlineReached {
            get {
                return ResourceManager.GetString("DeadlineReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the reunion {0} ?.
        /// </summary>
        public static string DoYouWantDeleteReunion {
            get {
                return ResourceManager.GetString("DoYouWantDeleteReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Reunion.
        /// </summary>
        public static string EditReunion {
            get {
                return ResourceManager.GetString("EditReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The participants may not use the same mail address.
        /// </summary>
        public static string ErrAmbigiousParticipantEmail {
            get {
                return ResourceManager.GetString("ErrAmbigiousParticipantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string ErrAnErrorHasOccurred {
            get {
                return ResourceManager.GetString("ErrAnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should enter one participant at minimum.
        /// </summary>
        public static string ErrEnterParticipants {
            get {
                return ResourceManager.GetString("ErrEnterParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorViewTitle {
            get {
                return ResourceManager.GetString("ErrorViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please mark the date ranges in the calendar for a possible meeting..
        /// </summary>
        public static string ErrPossibleDatesMissing {
            get {
                return ResourceManager.GetString("ErrPossibleDatesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is required.
        /// </summary>
        public static string ErrRequired {
            get {
                return ResourceManager.GetString("ErrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of reunion allready exists.
        /// </summary>
        public static string ErrReunionNameAllreadyExist {
            get {
                return ResourceManager.GetString("ErrReunionNameAllreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; may have at maximum {1} characters.
        /// </summary>
        public static string ErrTextTooLong {
            get {
                return ResourceManager.GetString("ErrTextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields have not been filled in correctly.
        /// </summary>
        public static string ErrValidationErrorsOccured {
            get {
                return ResourceManager.GetString("ErrValidationErrorsOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of reunion.
        /// </summary>
        public static string FinalDate {
            get {
                return ResourceManager.GetString("FinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///{0} will be taking place on &lt;b&gt;{1}&lt;/b&gt;.
        ///
        ///All participants have been informed. We are waiting for their final commitments..
        /// </summary>
        public static string FinalInvitationMailBody {
            get {
                return ResourceManager.GetString("FinalInvitationMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///{0} will be taking place on &lt;b&gt;{1}&lt;/b&gt;.
        ///
        ///By this &lt;a href=&quot;{2}&quot;&gt;link&lt;/a&gt; you can go to the website and finally confirm your participation.
        ///
        ///If you already have indicated that you can not come on that day you needn&apos;t give any additional cancellation.
        ///
        ///This message was created automatically by the web service &lt;b&gt;Reunion&lt;/b&gt;..
        /// </summary>
        public static string FinalInvitationMailBodyParticipant {
            get {
                return ResourceManager.GetString("FinalInvitationMailBodyParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///{0} will be taking place on {2}.
        ///
        ///By this Link ({3}) you can go to the website and finally confirm your participation.
        ///
        ///If you already have indicated that you can not come on that day you needn&apos;t give any additional cancellation.
        ///
        ///This message was created automatically by the web service Reunion..
        /// </summary>
        public static string FinalInvitationMailBodyParticipantText {
            get {
                return ResourceManager.GetString("FinalInvitationMailBodyParticipantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final invitation to {0}.
        /// </summary>
        public static string FinalInvitationMailSubject {
            get {
                return ResourceManager.GetString("FinalInvitationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final invitation sent.
        /// </summary>
        public static string FinallyInvitated {
            get {
                return ResourceManager.GetString("FinallyInvitated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose ....
        /// </summary>
        public static string FinallyInvite {
            get {
                return ResourceManager.GetString("FinallyInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerlach und Sanabria Partnerschaft, Softwareingenieure.
        /// </summary>
        public static string GerlachIt {
            get {
                return ResourceManager.GetString("GerlachIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string Haftpflichtversicherung {
            get {
                return ResourceManager.GetString("Haftpflichtversicherung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At home and abroad, excluding US and US territories.
        /// </summary>
        public static string HaftpflichtversicherungDetails {
            get {
                return ResourceManager.GetString("HaftpflichtversicherungDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}! &lt;br&gt;
        ///Could you please mark your preferred dates regarding the meeting in the calendar ?.
        /// </summary>
        public static string HelloParticipant {
            get {
                return ResourceManager.GetString("HelloParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        public static string HelloYou {
            get {
                return ResourceManager.GetString("HelloYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal info.
        /// </summary>
        public static string ImpressumViewTitle {
            get {
                return ResourceManager.GetString("ImpressumViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to organize a meeting with friends, but don&apos;t know how to find a suitable day, 
        ///when as many people as possible have time?
        ///&lt;span class=&quot;productname&quot;&gt;Reunion&lt;/span&gt; is a semi-automatic system
        ///to help you to find an appointment.
        ///&lt;span class=&quot;productname&quot;&gt;Reunion&lt;/span&gt; contacts the participants individually 
        ///and asks them about their appointment proposals. 
        ///If there are conflicting schedules, it tries to solve it as fair as possible.
        ///If some participants don&apos;t answer, the web service asks t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a participant of a concrete meeting, you&apos;ll get an email from the respective organizer.
        ///That email contains a personal link to the page of your preferences for a possible date. 
        ///Please check your mailbox for appropriate messages or contact the organizer of the
        ///meeting directly. A registration on this web portal isn&apos;t necessary..
        /// </summary>
        public static string IntroParticipant {
            get {
                return ResourceManager.GetString("IntroParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For participants of a meeting.
        /// </summary>
        public static string IntroParticipantTitle {
            get {
                return ResourceManager.GetString("IntroParticipantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For organizers of meetings.
        /// </summary>
        public static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You accepted.
        /// </summary>
        public static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}
        ///
        ///To find a suitable date, the web service &quot;Reunion&quot; is used.
        ///&quot;Reunion&quot; may have sent you already a mail from {3} containing a personal link to &quot;Reunion&quot;.
        ///If you did not receive the email yet, please also check your spam folder.
        ///With the containing link you can immediately enter your preferred dates without having to log you in particulary.
        ///If you can not come in the given period, you can note this on that site as well.
        ///.
        /// </summary>
        public static string InvitationMailBody {
            get {
                return ResourceManager.GetString("InvitationMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}&lt;br&gt;
        ///&lt;br&gt;
        ///To find a suitable date, the web service &quot;Reunion&quot; is used.&lt;br&gt;
        ///With this &lt;a href=&quot;{3}&quot;&gt;link&lt;/a&gt; you can - without having to log you in particular - immediately enter your preferred dates.&lt;br&gt;
        ///If you can not come in the given period, you can note this on that site as well.&lt;br&gt;
        ///.
        /// </summary>
        public static string InvitationMailBodyParticipant {
            get {
                return ResourceManager.GetString("InvitationMailBodyParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}
        ///
        ///To find a suitable date, the web service &quot;Reunion&quot; is used.
        ///With this link ({3}) you can immediately enter your preferred dates and update them at any time.
        ///If you can not come in the given period, you can note this on that site as well.
        ///.
        /// </summary>
        public static string InvitationMailBodyParticipantText {
            get {
                return ResourceManager.GetString("InvitationMailBodyParticipantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation {0}.
        /// </summary>
        public static string InvitationMailSubject {
            get {
                return ResourceManager.GetString("InvitationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have rejected.
        /// </summary>
        public static string InvitationRejected {
            get {
                return ResourceManager.GetString("InvitationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunion canceled.
        /// </summary>
        public static string InvitationStopped {
            get {
                return ResourceManager.GetString("InvitationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation text.
        /// </summary>
        public static string InvitationTextLabel {
            get {
                return ResourceManager.GetString("InvitationTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding {0} your action is required.&lt;br&gt;
        ///&lt;a href=&quot;{1}&quot;&gt;Reunion&lt;/a&gt;.
        /// </summary>
        public static string KnockMailBody {
            get {
                return ResourceManager.GetString("KnockMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - status update.
        /// </summary>
        public static string KnockMailSubject {
            get {
                return ResourceManager.GetString("KnockMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_DE {
            get {
                return ResourceManager.GetString("Language_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_EN {
            get {
                return ResourceManager.GetString("Language_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicate only indirectly over me.
        /// </summary>
        public static string LetAdminForwardMailToParticipantOnly {
            get {
                return ResourceManager.GetString("LetAdminForwardMailToParticipantOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string LockedOutViewTitle {
            get {
                return ResourceManager.GetString("LockedOutViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ongoing planning.
        /// </summary>
        public static string ManageExistingReunion {
            get {
                return ResourceManager.GetString("ManageExistingReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe.
        /// </summary>
        public static string Maybe {
            get {
                return ResourceManager.GetString("Maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send also first invitation mail by &lt;span class=&apos;productname&apos;&gt;Reunion&lt;/span&gt;..
        /// </summary>
        public static string MayContactByWebservice {
            get {
                return ResourceManager.GetString("MayContactByWebservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemAboutTitel {
            get {
                return ResourceManager.GetString("MenuItemAboutTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuItemContactTitel {
            get {
                return ResourceManager.GetString("MenuItemContactTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuItemHomeTitel {
            get {
                return ResourceManager.GetString("MenuItemHomeTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal info.
        /// </summary>
        public static string MenuItemImpressumTitel {
            get {
                return ResourceManager.GetString("MenuItemImpressumTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuItemLoginTitle {
            get {
                return ResourceManager.GetString("MenuItemLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reunions.
        /// </summary>
        public static string MenuItemMyReunionsTitel {
            get {
                return ResourceManager.GetString("MenuItemMyReunionsTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string MenuItemRegisterTitle {
            get {
                return ResourceManager.GetString("MenuItemRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello participant,
        ///
        ///Unfortunately we couldn&apos;t find a common date.
        ///The most promising dates so far are:
        ///
        ///{1}
        ///
        ///Unfortunately you didn&apos;t give any details on these days.
        ///
        ///The calendar with your details can be reached via the following link:
        ///
        ///&lt;a href=&quot;{2}&quot;&gt; Reunion &lt;/a&gt;
        ///
        ///---------------------------------------------------------------------------
        ///This email was generated automatically by &lt;b&gt; Reunion &lt;/ b&gt;.
        ///---------------------------------------------------------------------------
        ///
        ///
        ///.
        /// </summary>
        public static string MissingDayNotificationBody {
            get {
                return ResourceManager.GetString("MissingDayNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - missing some information.
        /// </summary>
        public static string MissingDayNotificationMailSubject {
            get {
                return ResourceManager.GetString("MissingDayNotificationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the following months there is still missing your statement: {0}.
        /// </summary>
        public static string MonthsMissing {
            get {
                return ResourceManager.GetString("MonthsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More About &lt;span class=&quot;productname&quot;&gt;Reunion&lt;/span&gt;.
        /// </summary>
        public static string MoreAboutReunion {
            get {
                return ResourceManager.GetString("MoreAboutReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string MoreAboutReunionTitle {
            get {
                return ResourceManager.GetString("MoreAboutReunionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not answered.
        /// </summary>
        public static string NotAnswered1 {
            get {
                return ResourceManager.GetString("NotAnswered1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not answered.
        /// </summary>
        public static string NotAnswered2 {
            get {
                return ResourceManager.GetString("NotAnswered2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation not sent yet.
        /// </summary>
        public static string NotInvitatedYet {
            get {
                return ResourceManager.GetString("NotInvitatedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet.
        /// </summary>
        public static string NotYet {
            get {
                return ResourceManager.GetString("NotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ParticipantName {
            get {
                return ResourceManager.GetString("ParticipantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ParticipantStatus {
            get {
                return ResourceManager.GetString("ParticipantStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Day.
        /// </summary>
        public static string PerfectDay {
            get {
                return ResourceManager.GetString("PerfectDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation sent.
        /// </summary>
        public static string PrimaryInvitationSent {
            get {
                return ResourceManager.GetString("PrimaryInvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        public static string ProposedDates {
            get {
                return ResourceManager.GetString("ProposedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reunion will take place on &lt;b&gt;{0}&lt;/b&gt;..
        /// </summary>
        public static string QuestionFinalInvitation {
            get {
                return ResourceManager.GetString("QuestionFinalInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to didn&apos;t filled in important days.
        /// </summary>
        public static string ReactionOnFeedbackMissing {
            get {
                return ResourceManager.GetString("ReactionOnFeedbackMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusing participants.
        /// </summary>
        public static string RefusingParticipants {
            get {
                return ResourceManager.GetString("RefusingParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove me from mailing list.
        /// </summary>
        public static string RejectComplete {
            get {
                return ResourceManager.GetString("RejectComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused.
        /// </summary>
        public static string Rejected1 {
            get {
                return ResourceManager.GetString("Rejected1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final invitation refused.
        /// </summary>
        public static string RejectedFinallyInvitation {
            get {
                return ResourceManager.GetString("RejectedFinallyInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, I can&apos;t come that day..
        /// </summary>
        public static string RejectFinaldateOnly {
            get {
                return ResourceManager.GetString("RejectFinaldateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///{0} can not take place on {1} due to too many short incoming rejections.
        ///We are currently trying to find an alternative date.
        ///
        ///&lt;a href=&quot;{2}&quot;&gt;Reunion code&lt;/a&gt;.
        /// </summary>
        public static string RejectionMailBodyParticipant {
            get {
                return ResourceManager.GetString("RejectionMailBodyParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection {0}.
        /// </summary>
        public static string RejectionMailSubject {
            get {
                return ResourceManager.GetString("RejectionMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend final invitation.
        /// </summary>
        public static string ResendFinalInvitation {
            get {
                return ResourceManager.GetString("ResendFinalInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend invitation.
        /// </summary>
        public static string ResendInvitation {
            get {
                return ResourceManager.GetString("ResendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a New Reunion.
        /// </summary>
        public static string ReunionCreate {
            get {
                return ResourceManager.GetString("ReunionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit reunion.
        /// </summary>
        public static string ReunionEditHint {
            get {
                return ResourceManager.GetString("ReunionEditHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reunions.
        /// </summary>
        public static string ReunionManageTitle {
            get {
                return ResourceManager.GetString("ReunionManageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ReunionNameLabel {
            get {
                return ResourceManager.GetString("ReunionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ReunionSettings {
            get {
                return ResourceManager.GetString("ReunionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants (except you).
        /// </summary>
        public static string ReunionSettingsFriends {
            get {
                return ResourceManager.GetString("ReunionSettingsFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReunionStatusTitle {
            get {
                return ResourceManager.GetString("ReunionStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunion.
        /// </summary>
        public static string ReunionTitle {
            get {
                return ResourceManager.GetString("ReunionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered office.
        /// </summary>
        public static string Sitz {
            get {
                return ResourceManager.GetString("Sitz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to reunite.
        /// </summary>
        public static string StartPageHeader {
            get {
                return ResourceManager.GetString("StartPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start planning reunion. Send invitations..
        /// </summary>
        public static string StartPlanning {
            get {
                return ResourceManager.GetString("StartPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start the search for a suitable date, if necessary, some of the participants must be first contacted from your own email address. That is necessary to get the participants not to throw away the mail invitation automatically sent from the web server&apos;s email address. If you click on &quot;start planning&quot; your e-mail program will open with a pre-filled email. Please read it carefully and send it from your email address afterwards..
        /// </summary>
        public static string StartPlanningConfirmation {
            get {
                return ResourceManager.GetString("StartPlanningConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started yet.
        /// </summary>
        public static string StatusCreated {
            get {
                return ResourceManager.GetString("StatusCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final invitations have been sent..
        /// </summary>
        public static string StatusFinallyInvitating {
            get {
                return ResourceManager.GetString("StatusFinallyInvitating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no date for the meeting to be found. The meeting will not take place..
        /// </summary>
        public static string StatusFinishedFailed {
            get {
                return ResourceManager.GetString("StatusFinishedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All required participants will come. The meeting takes place..
        /// </summary>
        public static string StatusFinishedSucceeded {
            get {
                return ResourceManager.GetString("StatusFinishedSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found a date !.
        /// </summary>
        public static string StatusProposingDate {
            get {
                return ResourceManager.GetString("StatusProposingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SubmitNewReunion {
            get {
                return ResourceManager.GetString("SubmitNewReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Date Proposals.
        /// </summary>
        public static string TitleParticipantView {
            get {
                return ResourceManager.GetString("TitleParticipantView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my preferences ....
        /// </summary>
        public static string UpdateMyPreferences {
            get {
                return ResourceManager.GetString("UpdateMyPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose.
        /// </summary>
        public static string UpdateParticipantsPreferences {
            get {
                return ResourceManager.GetString("UpdateParticipantsPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number.
        /// </summary>
        public static string UStIDNr {
            get {
                return ResourceManager.GetString("UStIDNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunion is a webservice, with which many participants of a reunion can negotiate a day for the meeting.
        ///The participants are automatically contacted by the service via email and fill in their personal 
        ///preferences regarding the meeting in a personal calendar:.
        /// </summary>
        public static string VisionText1 {
            get {
                return ResourceManager.GetString("VisionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants can update their calendar at any time, 
        ///even after a final date has already been set..
        /// </summary>
        public static string VisionText2 {
            get {
                return ResourceManager.GetString("VisionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organizer will be informed by the service, when.
        /// </summary>
        public static string VisionText3 {
            get {
                return ResourceManager.GetString("VisionText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;there is a possible date for all participants whose participation is required. &lt;/li&gt;
        ///&lt;li&gt;a participant does not respond &lt;/li&gt;
        ///&lt;li&gt;finally all participants have agreed&lt;/li&gt;
        ///&lt;li&gt;the date entered as the deadline was reached and no appointment could be found &lt;/li&gt;.
        /// </summary>
        public static string VisionText4 {
            get {
                return ResourceManager.GetString("VisionText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is &lt;span class=&quot;productname&quot;&gt;Reunion&lt;/span&gt;?.
        /// </summary>
        public static string WhatIsReunion {
            get {
                return ResourceManager.GetString("WhatIsReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When can you come ?.
        /// </summary>
        public static string WhenDoYouCome {
            get {
                return ResourceManager.GetString("WhenDoYouCome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
